//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        public Journey()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int JourneyId { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.DateTime dDate { get; set; }
        public decimal Cost { get; set; }
        public string DeptTime { get; set; }
        public string ArrTime { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
