//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public int JourneyId { get; set; }
        public decimal Price { get; set; }
        public string Class { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Seats { get; set; }
        public string SeatsDetails { get; set; }
    
        public virtual Journey Journey { get; set; }
    }
}
